MessageBuffer usage improvement
EmbeddedRPC/erpc pull request #258
Opened 2022-03-07 14:08 UTC by Hadatko

Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

# Pull request

**Choose Correct**

- [X] bug
- [ ] feature

**Describe the pull request**

Described in linked issues

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [X] I read Contribution details and did appropriate actions.
- [X] PR code is tested.
- [X] PR code is formatted.

**Additional context**

2022-03-08 06:29 UTC, amgross requested changes

2022-03-08 15:20 UTC, Hadatko commented on erpc_c/infra/erpc_message_buffer.cpp
>              (void)memcpy(m_buf, data, length);
Agree

2022-03-08 15:32 UTC, Hadatko commented
Thank you for PR review. I did it too quickly. 
I accidentaly force pushed (in current job customer is asking less commits more force pushes :D )

2022-03-09 05:13 UTC, amgross approved these changes

2022-03-09 05:14 UTC, amgross commented
BTW, I found out I was wrong in comment above and it is OK to check NULL with `if(pointer)`, but still I don't like it and it is better to have uniformity

2022-03-09 08:35 UTC, Hadatko commented
> BTW, I found out I was wrong in comment above and it is OK to check NULL with `if(pointer)`, but still I don't like it and it is better to have uniformity

No problem. Misra is also suggesting explicit conditions. Thank you for your engagement.

2022-03-10 13:49 UTC, MichalPrincNXP approved these changes

2022-03-10 13:49 UTC, merged

2022-03-10 13:50 UTC, MichalPrincNXP commented
Thank you for the effort!