improved codec function to use reference instead of address
EmbeddedRPC/erpc pull request #324
Opened 2022-11-23 15:37 UTC by Hadatko

Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

# Pull request

**Choose Correct**

- [ ] bug
- [X] feature

**Describe the pull request**

 safer as prevent passing nullptr

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [X] I read Contribution details and did appropriate actions.
- [x] PR code is tested.
- [x] PR code is formatted.
- [x] Allow edits from maintainers pull request option is set (recommended).

**Additional context**

2022-11-23 17:01 UTC, Hadatko commented
@MichalPrincNXP i think this one can be merged.

2023-01-24 13:24 UTC, MichalPrincNXP requested changes
Could you please 
- resolve conflicts
- update comments in individual changed functions description (params order)

2023-01-26 21:08 UTC, MichalPrincNXP approved these changes

2023-01-26 21:09 UTC, merged

2023-01-26 21:09 UTC, MichalPrincNXP commented
Thank you for the effort and the patience!